---
name: Build LaTeX document
on:
  push:
    branches:
      - master

jobs:
  build-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: latex-builder
          cache-from: type=registry,ref=latex-builder
          cache-to: type=inline

      - name: Build LaTeX document
        run: docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD:/data" latex-builder resume.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
